#+startup: inlineimages entitiespretty
#+tags: @Tutorials(T) @Articles(A) @Projects(P)
#+tags: hugo(h) networks(n)
#+hugo_base_dir: ../
#+author: jeanjayquitayen


* Tutorials                                                      :@Tutorials:
** STARTED Testing Network Speed                                  :networks:
:PROPERTIES:
:EXPORT_DATE: <2023-04-23 Sun>
:EXPORT_FILE_NAME: my-first-post
:END:
We all know how it feels when the network speed is problematic and you constantly get disconnected from the internet.

There are several approach to testing a network depending on the nature of it. Common factors are your ISP's internet speed or you local network.
*** Testing the Internet Speed
There are serveral browser based speedtest tools that can be used to check you internet speed.
 The most commonly used is the speedtest.net.



** TODO What you need to know about internet speedtest tools.

** TODO Convert you PLDT Prepaid Modem into an Access Point.

** TODO Set up a wifi voucher system using Tplink Omada.

** TODO Django Token Authentication using Durin

** TODO How to use Multipass

** DONE Testing Django Rest API with Pytest
:PROPERTIES:
:EXPORT_FILE_NAME: Unittesting-with-drf
:EXPORT_DATE: <2023-05-14 Sun>
:END:
If you are wondering how to use pytest with Django DRF then you are in for some treat.
Pytest is great for unit testing but when working with DRF some work needs to be done.
Luckily there is =drf_pytest= to help with structuring the test cases.

*** Project Setup
We will be using the Django blog project for the tutorial.
#+begin_src sh
  django-admin start project blog
#+end_src

* Articles                                                        :@Articles:

** TODO My second post                                                :hugo:
:PROPERTIES:
:EXPORT_DATE: <2023-04-23 Sun>
:EXPORT_FILE_NAME: my-second-post
:END:
*** The life of an Engineer
Their life started okay.

** TODO Using RFC 6349 for Network Testing                        :networks:
:PROPERTIES:
:EXPORT_DATE: <2023-04-23 Sun>
:EXPORT_FILE_NAME: TCP-Network-measurement
:EXPORT_HUGO_PAIRED_SHORTCODES: katex
:END:
When we talk about testing the network speed it is always the web browser based speed measurement tools like Ookla or Fast.com. These tools will give you the download and upload speed as well as the latency and ping.


#+hugo: {{< katex >}}

\(f(a,b,c) = (a^2+b^2+c^2)^3\)


% KaTeX inline notation

Inline notation: \\(\varphi = \dfrac{1+\sqrt5}{2}= 1.6180339887…\\)


* Projects                                                        :@Projects:

** Aquarium Automatic Water Change

